---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: silverblue-custom
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://download.docker.com/linux/fedora/docker-ce.repo
      copr:
        - birkch/HeadsetControl
    install:
      packages:
        # GUI apps on host for better integration
        - gnome-clocks
        - gnome-tweaks
        - nextcloud-client
        - nextcloud-client-nautilus
        - xournal

        # Tilix as default terminal
        - tilix
        - tilix-nautilus

        # Official docker-engine release
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

        # HP printer and scanner drivers
        - hplip
        - sane-backends-drivers-scanners
        - simple-scan

        # Headset control (COPR: birkch/HeadsetControl)
        - HeadsetControl

        # Logitech receiver
        - solaar

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.google.Chrome
          - com.mattjakeman.ExtensionManager
          - com.visualstudio.code
          - dev.restfox.Restfox
          - no.mifi.losslesscut
          - org.gnome.Calculator
          - org.gnome.Evince
          - org.gnome.Loupe
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.jellyfin.JellyfinDesktop
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
        remove:
          - com.github.iwalton3.jellyfin-media-player
          - dev.zed.Zed
          - org.gnome.Extensions
          - org.gnome.Totem
          - org.mozilla.firefox
          - rest.insomnia.Insomnia
      - scope: user

  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - Caffeine
      - Docker
      - HeadsetControl

  - type: signing
